# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9c78544908be366fa25e7442ee916dda535270801d3018747260c587ecf1b4b756c91c0737b47a540477102ff0966130024e07466622bcde65a8b71c93f9e3a

test:
  secret_key_base: 43b657dbadb6706a11ff920f32024c294a2eafa2be0d35327980b1bed38b3df976086114029fb1c265b098756ce09826844a18b596642fde778f47f8af347f19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
